spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PlayersDB
    username: postgres
    password: nmtprG
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://212.22.93.198:5432/CheatersDB
    username: postgres
    password: nmtprG
