spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PlayersStats
    username: postgres
    password: nmtprG
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
